credentials:
  usernames: admin
    admin:
      email: admin@tuempresa.com
      name: Administrador
      password: admin123
    juan:
      email: juan@tuempresa.com
      name: Juan Pérez
      password: $2b$12$XyZaBcDeFgHiJkLmNoPqRsTuVwXyZ1Y2X3W4V5U6T7S8R9Q0P
    ana:
      email: ana@tuempresa.com
      name: Ana López
      password: $2b$12$AbCdEfGhIjKlMnOpQrStUvWxYz1234567890abcdefghiJ
cookie:
  expiry_days: 30
  key: regenerativo2025claveunica
  name: forrajero_regenerativo
preauthorized:
  emails:
    - admin@tuempresa.com
    - juan@tuempresa.com
    - ana@tuempresa.com
