credentials:
  usernames:
    admin:
      email: admin@tuempresa.com
      name: Administrador
      password: $2b$12$XxXDw83MsoXhxe0Opny1PeoLuSH5dgSUVu992lhl.sFv/AgSUkB8G
    juan:
      email: juan@tuempresa.com
      name: Juan Pérez
      password: $2b$12$nIPssYVHEFxyEKNCyrgeAO0PIzcYXBfNlWTB7WgpDi3.l4EbbrloC
    ana:
      email: ana@tuempresa.com
      name: Ana López
      password: $2b$12$SPxwWIpTHNHO7AtzucoXyu9U0Ia1Xj8SDC9sT.DtwOOFDDgtR8l7m
cookie:
  expiry_days: 30
  key: regenerativo2025claveunica
  name: forrajero_regenerativo
preauthorized:
  emails:
    - admin@tuempresa.com
    - juan@tuempresa.com
    - ana@tuempresa.com
