credentials:
  usernames:
    admin: admin
      email: admin@tuempresa.com
      name: Administrador
      password: $2b$12$9fK8v7c6d5e4f3g2h1i0j.kLmNoPqRsTuVwXyZ1Y2X3W4V5U6T7S
    juan:
      email: juan@tuempresa.com
      name: Juan Pérez
      password: $2b$12$XyZaBcDeFgHiJkLmNoPqRsTuVwXyZ1Y2X3W4V5U6T7S8R9Q0P
    ana:
      email: ana@tuempresa.com
      name: Ana López
      password: $2b$12$AbCdEfGhIjKlMnOpQrStUvWxYz1234567890abcdefghiJ
cookie:
  expiry_days: 30
  key: regenerativo2025claveunica
  name: forrajero_regenerativo
preauthorized:
  emails:
    - admin@tuempresa.com
    - juan@tuempresa.com
    - ana@tuempresa.com
